apiVersion: v1
kind: Service
metadata:
  labels:
    app: ks-transport-controller
  name: ks-transport-controller
spec:
  ports:
  - name: metrics
    port: 8090
    targetPort: metrics
  - name: latency
    port: 2222
    targetPort: latency
  selector:
    name: transport-controller
